
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;
import javax.swing.JTable;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/AWTForms/Frame.java to edit this template
 */

/**
 *
 * @author User
 */
public class Attendance extends java.awt.Frame {

    /**
     * Creates new form Attendance
     */
    public Attendance() {
        initComponents();
        setSize(1280,720);
                ThemeManager.applyTheme(jPanel2);

        loadAttendance(jTable1);
        jTextField1.addFocusListener(new java.awt.event.FocusAdapter() {
        public void focusGained(java.awt.event.FocusEvent evt) {
            if (jTextField1.getText().equals("🔍 Search Employee")) {
                jTextField1.setText("");
            }
        }
        public void focusLost(java.awt.event.FocusEvent evt) {
            if (jTextField1.getText().trim().isEmpty()) {
                jTextField1.setText("🔍 Search Employee");
                loadAttendance(jTable1);
            }
        }
    });
    
    jTextField1.getDocument().addDocumentListener(new javax.swing.event.DocumentListener() {
        public void insertUpdate(javax.swing.event.DocumentEvent e) { search(); }
        public void removeUpdate(javax.swing.event.DocumentEvent e) { search(); }
        public void changedUpdate(javax.swing.event.DocumentEvent e) {}
        
        private void search() {
            javax.swing.SwingUtilities.invokeLater(() -> {
                String input = jTextField1.getText().trim();
                if (input.isEmpty() || input.equals("🔍 Search Employee")) {
                    loadAttendance(jTable1);
                    return;
                }
                try {
                    int empId = Integer.parseInt(input);
                    String sql = "SELECT PAYROLL_ID, EMP_ID, FIRST_NAME, LAST_NAME, JOB_ID, BASIC_SALARY, PAY_DATE, ALLOWANCE, DEDUCTION FROM PAYROLL WHERE EMP_ID = ?";
                    PreparedStatement ps = DatabaseConnection.getConnection().prepareStatement(sql);
                    ps.setInt(1, empId);
                    ResultSet rs = ps.executeQuery();
                    DefaultTableModel model = new DefaultTableModel(
                        new String[]{"Payroll ID","Emp ID","First Name","Last Name","Job ID","Basic Salary","Pay Date","Allowance","Deduction"}, 0
                    );
                    boolean found = false;
                    while (rs.next()) {
                        found = true;
                        model.addRow(new Object[]{
                            rs.getInt("PAYROLL_ID"), rs.getInt("EMP_ID"),
                            rs.getString("FIRST_NAME"), rs.getString("LAST_NAME"),
                            rs.getString("JOB_ID"), rs.getDouble("BASIC_SALARY"),
                            rs.getDate("PAY_DATE"), rs.getDouble("ALLOWANCE"),
                            rs.getDouble("DEDUCTION")
                        });
                    }
                    jTable1.setModel(model);
                    if (!found) {
                        javax.swing.JOptionPane.showMessageDialog(null, "No Data Found", "Search Result", javax.swing.JOptionPane.INFORMATION_MESSAGE);
                    }
                } catch (NumberFormatException ex) {
                    // لسا عم يكتب
                } catch (Exception ex) {
                    ex.printStackTrace();
                }
            });
        }
    });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("Attendance & Leave");

        jTextField1.setText("🔍 Search Employee");
        jTextField1.addActionListener(this::jTextField1ActionPerformed);

        jButton1.setText("Premission To Leave");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        jButton2.setText("Check out");
        jButton2.addActionListener(this::jButton2ActionPerformed);

        jButton3.setText("Check in");
        jButton3.addActionListener(this::jButton3ActionPerformed);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "EMP_ID", "FIRST_NAME", "LAST_NAME", "DATE", "CHECK_IN", "CHECK_OUT", "STATUS"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jButton4.setText("Back To Dashboard");
        jButton4.addActionListener(this::jButton4ActionPerformed);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 401, Short.MAX_VALUE)
                        .addComponent(jButton4)
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12))))
            .addComponent(jScrollPane1)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jTextField1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );

        add(jPanel2, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Exit the Application
     */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        int selectedRow = jTable1.getSelectedRow();
    if (selectedRow == -1) {
        javax.swing.JOptionPane.showMessageDialog(this, "Please select an employee first", "Warning", javax.swing.JOptionPane.WARNING_MESSAGE);
        return;
    }

    // الوقت الحالي
    java.time.LocalTime now = java.time.LocalTime.now();
    String currentTime = String.format("%02d:%02d", now.getHour(), now.getMinute());

    String time = (String) javax.swing.JOptionPane.showInputDialog(
        this, "Check In Time:", "Check In",
        javax.swing.JOptionPane.PLAIN_MESSAGE, null, null, currentTime
    );

    if (time == null) return; // ضغط Cancel

    try {
        int attendId = (int) jTable1.getValueAt(selectedRow, 0);
        String sql = "UPDATE ATTENDANCE_LEAVE SET CHECK_IN = ? WHERE ATTEND_ID = ?";
        PreparedStatement ps = DatabaseConnection.getConnection().prepareStatement(sql);
        ps.setString(1, time);
        ps.setInt(2, attendId);
        ps.executeUpdate();

        javax.swing.JOptionPane.showMessageDialog(this, "Check In recorded: " + time, "Success", javax.swing.JOptionPane.INFORMATION_MESSAGE);
        loadAttendance(jTable1);
    } catch (Exception e) {
        e.printStackTrace();
        javax.swing.JOptionPane.showMessageDialog(this, e.getMessage());
    }

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
          Dashboard dsh = new Dashboard();
        
       dsh.show();
        
        dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int selectedRow = jTable1.getSelectedRow();
    if (selectedRow == -1) {
        javax.swing.JOptionPane.showMessageDialog(this, "Please select an employee first", "Warning", javax.swing.JOptionPane.WARNING_MESSAGE);
        return;
    }
    
    String firstName = jTable1.getValueAt(selectedRow, 2).toString();
    String lastName = jTable1.getValueAt(selectedRow, 3).toString();
    String empName = firstName + " " + lastName;
    
    PermissionToLeave dialog = new PermissionToLeave(null, true, this);
    dialog.setEmployeeData(empName);
    dialog.setLocationRelativeTo(null);
    dialog.setVisible(true);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
        String input = jTextField1.getText().trim();
    
    // إذا فاضي أو placeholder ارجع كل البيانات
    if (input.isEmpty() || input.equals("🔍 Search Employee")) {
        loadAttendance(jTable1);
        return;
    }
    
    try {
        int empId = Integer.parseInt(input);
        
        String sql = "SELECT ATTEND_ID, EMP_ID, FIRST_NAME, LAST_NAME, ATTEND_DATE, CHECK_IN, CHECK_OUT, STATUS FROM ATTENDANCE_LEAVE WHERE EMP_ID = ?";
        PreparedStatement ps = DatabaseConnection.getConnection().prepareStatement(sql);
        ps.setInt(1, empId);
        ResultSet rs = ps.executeQuery();
        
        DefaultTableModel model = new DefaultTableModel(
            new String[]{"Attend ID","Emp ID","First Name","Last Name","Date","Check In","Check Out","Status"}, 0
        );
        
        boolean found = false;
        while (rs.next()) {
            found = true;
            model.addRow(new Object[]{
                rs.getInt("ATTEND_ID"), rs.getInt("EMP_ID"),
                rs.getString("FIRST_NAME"), rs.getString("LAST_NAME"),
                rs.getDate("ATTEND_DATE"), rs.getString("CHECK_IN"),
                rs.getString("CHECK_OUT"), rs.getString("STATUS")
            });
        }
        
        jTable1.setModel(model);
        
        if (!found) {
            javax.swing.JOptionPane.showMessageDialog(this, "No Data Found", "Search Result", javax.swing.JOptionPane.INFORMATION_MESSAGE);
        }
        
    } catch (NumberFormatException e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Please enter a valid Employee ID (numbers only)", "Invalid Input", javax.swing.JOptionPane.WARNING_MESSAGE);
    } catch (Exception e) {
        e.printStackTrace();
        javax.swing.JOptionPane.showMessageDialog(this, e.getMessage());
    }
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        int selectedRow = jTable1.getSelectedRow();
    if (selectedRow == -1) {
        javax.swing.JOptionPane.showMessageDialog(this, "Please select an employee first", "Warning", javax.swing.JOptionPane.WARNING_MESSAGE);
        return;
    }

    java.time.LocalTime now = java.time.LocalTime.now();
    String currentTime = String.format("%02d:%02d", now.getHour(), now.getMinute());

    String time = (String) javax.swing.JOptionPane.showInputDialog(
        this, "Check Out Time:", "Check Out",
        javax.swing.JOptionPane.PLAIN_MESSAGE, null, null, currentTime
    );

    if (time == null) return;

    try {
        int attendId = (int) jTable1.getValueAt(selectedRow, 0);
        String sql = "UPDATE ATTENDANCE_LEAVE SET CHECK_OUT = ? WHERE ATTEND_ID = ?";
        PreparedStatement ps = DatabaseConnection.getConnection().prepareStatement(sql);
        ps.setString(1, time);
        ps.setInt(2, attendId);
        ps.executeUpdate();

        javax.swing.JOptionPane.showMessageDialog(this, "Check Out recorded: " + time, "Success", javax.swing.JOptionPane.INFORMATION_MESSAGE);
        loadAttendance(jTable1);
    } catch (Exception e) {
        e.printStackTrace();
        javax.swing.JOptionPane.showMessageDialog(this, e.getMessage());
    }
    }//GEN-LAST:event_jButton2ActionPerformed
public void loadAttendance(JTable jTable1) {
    try {
        String sql = "SELECT ATTEND_ID, EMP_ID, FIRST_NAME, LAST_NAME, ATTEND_DATE, CHECK_IN, CHECK_OUT, STATUS FROM ATTENDANCE_LEAVE";
        PreparedStatement ps = DatabaseConnection.getConnection().prepareStatement(sql);
        ResultSet rs = ps.executeQuery();

        DefaultTableModel model = new DefaultTableModel(
            new String[]{"Attend ID","Emp ID","First Name","Last Name","Date","Check In","Check Out","Status"}, 0
        );
        while (rs.next()) {
            model.addRow(new Object[]{
                rs.getInt("ATTEND_ID"), rs.getInt("EMP_ID"),
                rs.getString("FIRST_NAME"), rs.getString("LAST_NAME"),
                rs.getDate("ATTEND_DATE"), rs.getString("CHECK_IN"),
                rs.getString("CHECK_OUT"), rs.getString("STATUS")
            });
        }
        jTable1.setModel(model);
    } catch (Exception e) { e.printStackTrace(); }
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Attendance().setVisible(true);
            }
         });
    }

public void addPendingRequest(String empName) {
    loadAttendance(jTable1);
}
        
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
