
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;
import javax.swing.JTable;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/AWTForms/Frame.java to edit this template
 */

/**
 *
 * @author User
 */
public class Payroll extends java.awt.Frame {

    /**
     * Creates new form Payroll
     */
    public Payroll() {
        initComponents();
                setSize(1280,720);
                ThemeManager.applyTheme(jPanel1);
                        loadPayroll(jTable1);
                        jTextField1.addFocusListener(new java.awt.event.FocusAdapter() {
        public void focusGained(java.awt.event.FocusEvent evt) {
            if (jTextField1.getText().equals("🔍 Search Employee")) {
                jTextField1.setText("");
            }
        }
        public void focusLost(java.awt.event.FocusEvent evt) {
            if (jTextField1.getText().trim().isEmpty()) {
                jTextField1.setText("🔍 Search Employee");
                loadPayroll(jTable1);
            }
        }
    });
    
    jTextField1.getDocument().addDocumentListener(new javax.swing.event.DocumentListener() {
        public void insertUpdate(javax.swing.event.DocumentEvent e) { search(); }
        public void removeUpdate(javax.swing.event.DocumentEvent e) { search(); }
        public void changedUpdate(javax.swing.event.DocumentEvent e) {}
        
        private void search() {
            javax.swing.SwingUtilities.invokeLater(() -> {
        String input = jTextField1.getText().trim();
        if (input.isEmpty() || input.equals("🔍 Search Employee")) {
            loadPayroll(jTable1);
            return;
        }
        try {
            int empId = Integer.parseInt(input);
            String sql = "SELECT p.PAYROLL_ID, p.EMP_ID, p.FIRST_NAME, p.LAST_NAME, p.JOB_ID, " +
                         "e.DEPARTMENT, p.BASIC_SALARY, p.PAY_DATE, p.ALLOWANCE, p.DEDUCTION " +
                         "FROM PAYROLL p LEFT JOIN EMPLOYEE e ON p.EMP_ID = e.EMP_ID " +
                         "WHERE p.EMP_ID = ?";
            PreparedStatement ps = DatabaseConnection.getConnection().prepareStatement(sql);
            ps.setInt(1, empId);
            ResultSet rs = ps.executeQuery();
            DefaultTableModel model = new DefaultTableModel(
                new String[]{"Payroll ID","Emp ID","First Name","Last Name","Job","Department","Basic Salary","Pay Date","Allowance","Deduction"}, 0
            );
            boolean found = false;
            while (rs.next()) {
                found = true;
                model.addRow(new Object[]{
                    rs.getInt("PAYROLL_ID"), rs.getInt("EMP_ID"),
                    rs.getString("FIRST_NAME"), rs.getString("LAST_NAME"),
                    rs.getString("JOB_ID"), rs.getString("DEPARTMENT"),
                    rs.getDouble("BASIC_SALARY"), rs.getDate("PAY_DATE"),
                    rs.getDouble("ALLOWANCE"), rs.getDouble("DEDUCTION")
                });
            }
            jTable1.setModel(model);
            if (!found) {
                javax.swing.JOptionPane.showMessageDialog(null, "No Data Found", "Search Result", javax.swing.JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (NumberFormatException ex) {
            // لسا عم يكتب
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    });
        }
    });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Payroll");

        jTextField1.setText("🔍 Search Employee");
        jTextField1.addActionListener(this::jTextField1ActionPerformed);

        jButton3.setText("Back To Dashboard");
        jButton3.setToolTipText("");
        jButton3.addActionListener(this::jButton3ActionPerformed);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "EMP_ID", "FIRST_NAME", "LAST_NAME", "JOB_ID", "BAIC_SALARY ", "PAY_DATE", "ALLOWNCE ", "DEDUCT"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton4.setText("Salary details");
        jButton4.addActionListener(this::jButton4ActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 401, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton4)
                    .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 372, Short.MAX_VALUE))
        );

        add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Exit the Application
     */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        Dashboard dsh = new Dashboard();
        
        dsh.show();
        
        dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
         Payroll_Details dialog = new Payroll_Details(null, true);
    dialog.setLocationRelativeTo(null);
    dialog.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed
public void loadPayroll(JTable jTable1) {
    try {
        String sql = "SELECT p.PAYROLL_ID, p.EMP_ID, p.FIRST_NAME, p.LAST_NAME, p.JOB_ID, " +
                     "e.DEPARTMENT, p.BASIC_SALARY, p.PAY_DATE, p.ALLOWANCE, p.DEDUCTION " +
                     "FROM PAYROLL p LEFT JOIN EMPLOYEE e ON p.EMP_ID = e.EMP_ID";
        PreparedStatement ps = DatabaseConnection.getConnection().prepareStatement(sql);
        ResultSet rs = ps.executeQuery();

        DefaultTableModel model = new DefaultTableModel(
            new String[]{"Payroll ID","Emp ID","First Name","Last Name","Job","Department","Basic Salary","Pay Date","Allowance","Deduction"}, 0
        );
        while (rs.next()) {
            model.addRow(new Object[]{
                rs.getInt("PAYROLL_ID"), rs.getInt("EMP_ID"),
                rs.getString("FIRST_NAME"), rs.getString("LAST_NAME"),
                rs.getString("JOB_ID"), rs.getString("DEPARTMENT"),
                rs.getDouble("BASIC_SALARY"), rs.getDate("PAY_DATE"),
                rs.getDouble("ALLOWANCE"), rs.getDouble("DEDUCTION")
            });
        }
        jTable1.setModel(model);
    } catch (Exception e) { e.printStackTrace(); }

}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Payroll().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
